const assert=require('node:assert/strict');
const {simulate}=require('./model.js');
const {aorticTrace}=require('./display.js');
const r=simulate(), before=JSON.stringify(r);
r.samples.forEach(Object.freeze);Object.freeze(r.samples);Object.freeze(r.metrics);Object.freeze(r);
const trace=aorticTrace(r);
const changed=r.samples.filter(s=>trace(s)!==s.pa);
assert(changed.length>0);
assert(changed.every(s=>s.qa<=0 && s.pa-trace(s)<=3.000001));
assert(changed.at(-1).t-changed[0].t<.032);
assert.equal(JSON.stringify(r),before,'Display leaves every model value unchanged');
for(const s of r.samples.filter(s=>s.qa>0))assert.equal(trace(s),s.pa,'Ejection unchanged');
const noEjection=simulate({aortic:0});
assert(noEjection.samples.every(s=>aorticTrace(noEjection)(s)===s.pa));
const leaking=simulate({aorticLeak:3}), leakTrace=aorticTrace(leaking);
assert(Math.max(...leaking.samples.map(s=>s.pa-leakTrace(s)))<.01);
console.log('PASS: display-only notch, bounded duration and depth, unchanged model and ejection, absent ejection, and leakage attenuation.');
